# fly.toml app configuration file for rec-cloud-backend
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "rec-cloud-backend"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  PYTHONPATH = "."
  TRADING_SYSTEM_HOST = "rec-cloud-backend.fly.dev"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

